#!/bin/bash

# Output file
output_file="aws_resources_with_tags.csv"

# Write the header to the output file
echo "Resource Type,Resource Name,Resource ARN,Tags" > $output_file

# Function to get tags for a specific resource type
get_tags() {
    resource_type=$1
    aws_command=$2
    name_key=$3

    resources=$(eval $aws_command | jq -r '.[] | @base64')

    for resource in $resources; do
        _jq() {
            echo ${resource} | base64 --decode | jq -r ${1}
        }

        resource_arn=$(_jq '.ResourceARN // .Arn')
        resource_name=$(_jq ".${name_key} // .Name // .ResourceName // .DBInstanceIdentifier // .FunctionName // .BucketName // .StackName")

        tags=$(aws resourcegroupstaggingapi get-tags --resource-arn $resource_arn | jq -r '.Tags | map("\(.Key)=\(.Value)") | join(",")')
        echo "${resource_type},${resource_name},${resource_arn},${tags}" >> $output_file
    done
}

# List of resource types and corresponding AWS CLI commands
declare -A resource_types=(
    ["ec2"]="aws ec2 describe-instances --query 'Reservations[].Instances[].{ResourceARN:InstanceId}'"
    ["s3"]="aws s3api list-buckets --query 'Buckets[].{ResourceARN:Name}'"
    ["lambda"]="aws lambda list-functions --query 'Functions[].{ResourceARN:FunctionArn, ResourceName:FunctionName}'"
    ["rds"]="aws rds describe-db-instances --query 'DBInstances[].{ResourceARN:DBInstanceArn, ResourceName:DBInstanceIdentifier}'"
    ["cloudformation"]="aws cloudformation list-stacks --query 'StackSummaries[].{ResourceARN:StackId, ResourceName:StackName}'"
    ["ec2-ami"]="aws ec2 describe-images --owners self --query 'Images[].{ResourceARN:ImageId}'"
    ["dynamodb"]="aws dynamodb list-tables --query 'TableNames[]' | jq -r '.[] | {ResourceARN: ("arn:aws:dynamodb:" + (aws configure get region) + ":" + (aws sts get-caller-identity --query Account --output text) + ":table/" + .)}'"
    ["sqs"]="aws sqs list-queues --query 'QueueUrls[] | {ResourceARN: ., ResourceName: (split("/")[4])}'"
    ["sns"]="aws sns list-topics --query 'Topics[].{ResourceARN:TopicArn}'"
    ["ecr"]="aws ecr describe-repositories --query 'repositories[].{ResourceARN:repositoryArn, ResourceName:repositoryName}'"
    ["ecs"]="aws ecs list-clusters --query 'clusterArns[]' | jq -r '.[] | {ResourceARN: .}'"
    ["elb"]="aws elb describe-load-balancers --query 'LoadBalancerDescriptions[].{ResourceARN:LoadBalancerName}'"
    ["alb"]="aws elbv2 describe-load-balancers --query 'LoadBalancers[].{ResourceARN:LoadBalancerArn, ResourceName:LoadBalancerName}'"
    ["cloudwatch"]="aws logs describe-log-groups --query 'logGroups[].{ResourceARN:arn, ResourceName:logGroupName}'"
    ["s3"]="aws s3api list-buckets --query 'Buckets[].{ResourceARN:Name}'"
    ["iam-role"]="aws iam list-roles --query 'Roles[].{ResourceARN:Arn, ResourceName:RoleName}'"
    ["iam-user"]="aws iam list-users --query 'Users[].{ResourceARN:Arn, ResourceName:UserName}'"
    ["iam-policy"]="aws iam list-policies --query 'Policies[].{ResourceARN:Arn, ResourceName:PolicyName}'"
    ["iam-group"]="aws iam list-groups --query 'Groups[].{ResourceARN:Arn, ResourceName:GroupName}'"
    ["cloudfront"]="aws cloudfront list-distributions --query 'DistributionList.Items[].{ResourceARN:ARN, ResourceName:Id}'"
    ["route53"]="aws route53 list-hosted-zones --query 'HostedZones[].{ResourceARN:Id, ResourceName:Name}'"
    ["autoscaling"]="aws autoscaling describe-auto-scaling-groups --query 'AutoScalingGroups[].{ResourceARN:AutoScalingGroupARN, ResourceName:AutoScalingGroupName}'"
    ["kms"]="aws kms list-keys --query 'Keys[].KeyId' | jq -r '.[] | {ResourceARN: ("arn:aws:kms:" + (aws configure get region) + ":" + (aws sts get-caller-identity --query Account --output text) + ":key/" + .)}'"
    ["elasticache"]="aws elasticache describe-cache-clusters --query 'CacheClusters[].{ResourceARN:CacheClusterId}'"
    ["emr"]="aws emr list-clusters --query 'Clusters[].{ResourceARN:Id, ResourceName:Name}'"
    ["cloudwatch-alarms"]="aws cloudwatch describe-alarms --query 'MetricAlarms[].{ResourceARN:AlarmArn, ResourceName:AlarmName}'"
)

# Iterate over resource types and get tags
for resource_type in "${!resource_types[@]}"; do
    get_tags $resource_type "${resource_types[$resource_type]}" "ResourceName"
done

echo "Resource information with tags has been written to $output_file"
